### ISSUE TITLE
packages.json not found

### ISSUE THREAD

**Issue by ynigun** [x1unix/go-playground#1]
After installation I run the command
`./playground`
And I get the response
`{"level":"info","ts":1579491429.3219748,"caller":"playground/main.go:55","msg":"GOROOT is \"/root/go\""}
"level":"info","ts":1579491429.3221557,"caller":"playground/main.go:56","msg":"Packages file is \"packages.json\""}{"level":"fatal","ts":1579491429.322225,"caller":"playground/main.go:33","msg":"failed to read packages file \"packages.json\": open packages.json: no such file or directory","stacktrace":"main.main\n\t/root/go-playground/cmd/playground/main.go:33\nruntime.main\n\t/root/go/src/runtime/proc.go:203"}
`

I found the problem is that the packages.json file is in the data directory
And an application is looking for ./packages.json instead of ./data/packages.json
The solution is to either copy the packages.json file or run the application with the flag
`./playground -f ./data/packages.json
`

**Comment by x1unix** [comment]
@ynigun thank you for the report. I'll update README

**Comment by x1unix** [comment]
Done - https://github.com/x1unix/go-playground/commit/60d66935518d27a4a1d666c947fd31aaaf14e2bd
