### ISSUE TITLE
code won't run

### ISSUE THREAD

**Issue by dcu** [x1unix/go-playground#101]
hello,

the following snippet fails with 502: https://goplay.tools/snippet/UIVCeAUVSyY

**Comment by x1unix** [comment]
@dcu Better Go Playground uses official Go playground backend to run code. Check if this snippet runs on official Go playground - https://go.dev/play/p/UIVCeAUVSyY

I was unable to run the code by myself.

**Comment by dcu** [comment]
what about wasm backend? it didn't work either

**Comment by x1unix** [comment]
@dcu tried Wasm backend - cannot reproduce.

https://goplay.tools/snippet/_gY0tANzJ4l

Can you open btowser DevTools and check what is going there?

![Screenshot_20220301-151859_Firefox](https://user-images.githubusercontent.com/9203548/156185956-f21da1d2-b22f-482b-ab08-8ed9e93a1eba.jpg)

**Comment by dcu** [comment]
it works, thanks!

**Comment by x1unix** [comment]
@dcu unfortunately WASM mode do not support third party packages for now and considered **Expermiental**
