### ISSUE TITLE
Defer “Goodbye”

### ISSUE THREAD

**Issue by wgeorgecook** [x1unix/go-playground#102]
I have a very dumb want to by default have a `defer fmt.Println(“Goodbye!”)` after the “Hello Playground” text in the default playground. Would we be opposed to me putting out a PR to include that here? Fun little way to introduce new folks to the defer functionality AND is a friendly little cleanup for whatever runs.

**Comment by x1unix** [comment]
@wgeorgecook default template is located at [src/components/editor/props.ts](https://github.com/x1unix/go-playground/blob/2668dbe18817d7693a5acf50df0eb209987b316c/web/src/components/editor/props.ts#L7).

I would like to hear feedback from more users regarding this idea.

Btw, there is a guide with examples that introduce some Go features. Maybe we can add defers section there?

<img width="376" alt="image" src="https://user-images.githubusercontent.com/9203548/156153490-f049afe0-b578-4730-934e-e2e08212e677.png">

**Comment by wgeorgecook** [comment]
@x1unix oh I like that idea too. It could be a lot more flushed than even the tour of Go has for their section on defer.
