### ISSUE TITLE
Support Go 1.18 with generics

### ISSUE THREAD

**Issue by serkodev** [x1unix/go-playground#105]
Is there any plan on supporting Go 1.18 ?

**Comment by x1unix** [comment]
@serkodev not sooner as 1.18 gets released.

**Comment by x1unix** [comment]
@serkodev at #113 I added support for GoTip Playground server which supports generics.

Currently editor don't support syntax highlight and syntax check for generics, but code should run fine.

You can switch to a GoTip server in settings:

<img width="582" alt="image" src="https://user-images.githubusercontent.com/9203548/157999179-1e7aca90-bc61-4bac-8610-105568250f33.png">

**Comment by serkodev** [comment]
@x1unix Nice work, good to hear that.
