### ISSUE TITLE
'Import' section small change

### ISSUE THREAD

**Issue by Metalscreame** [x1unix/go-playground#13]
Thanks for great work! 
Found one small annoying thing using import... 
![image](https://user-images.githubusercontent.com/18646505/79744376-ea2fbf80-830e-11ea-8c62-9b09d3ecb253.png)

If you need to add new import - you need to type `import "something"` one more time
Can you please change import default section to 
![image](https://user-images.githubusercontent.com/18646505/79744490-16e3d700-830f-11ea-9a32-47b117aa93b2.png)
as it is now in the default go playground
Thanks!

**Comment by x1unix** [comment]
Resolved by https://github.com/x1unix/go-playground/pull/14
