### ISSUE TITLE
Star

### ISSUE THREAD

**Issue by 89z** [x1unix/go-playground#134]
Good afternoon, sorry to bother you. For some reason, many people are giving star to my repo:

https://github.com/89z/googleplay

I saw you gave my repo a star, thank you. However I don't know how its happening. Can you say how you found my project? Is it linked somewhere?

**Comment by x1unix** [comment]
Hi, I don't remember exactly but there is a **Explore repositories** section at GitHub feed page which recommends some repos.

Also, I recommend to take a look at **Insights** page (**Traffic** section) to see websites that refer to your repo.
