### ISSUE TITLE
Vertically display for Output panel

### ISSUE THREAD

**Issue by vuon9** [x1unix/go-playground#136]
As a developer, I would like to ask for vertical panel of output panel
So, I could maximize using the width of the Go playground in big monitor.

I tried with inspect element to visualize it 😂
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/3168632/158988340-eaf1d8d2-71c1-4feb-abc1-97c671123ad5.png">

I assume this one could be a new setting item as well.

**Comment by x1unix** [comment]
@vuon9 this can be considered as idea in future release.

Feel free to submit a PR :)

**Comment by x1unix** [comment]
@vuon9 I was thinking about adding a button at the panel itself because looks like that not a lot of people actually using **Settings** menu.

**Comment by vuon9** [comment]
I see. I would like to give it a try 🗡️

**Comment by x1unix** [comment]
@vuon9 see https://github.com/x1unix/go-playground/pull/147

**Comment by vuon9** [comment]
oh wow u did it. that's amazing!! 🤩
i actually just did some draft code so it hasnt been completed as PR.

Thank you so much @x1unix 😍😍
