### ISSUE TITLE
Shift+Enter: Add new line after current line, jump to it

### ISSUE THREAD

**Issue by DamianFekete** [x1unix/go-playground#157]
Hi Denis,

If not too much trouble, it would be nice if `Shift+Enter` would not break the current line (as `Enter` does), and it would instead jump to the end of line and only then add the new line.

```
Some|{Shift+Enter} text
Another line
```
==>
```
Some text
|
Another line
```

Thank you for the playground.

**Comment by x1unix** [comment]
@DamianFekete what is the current behavior for VS Code?

**Comment by DamianFekete** [comment]
@x1unix, this would be the default behavior in the editor:
```
{ "key": "shift+enter",           "command": "editor.action.insertLineAfter",
                                     "when": "editorTextFocus && !editorReadonly" },
```

**Comment by x1unix** [comment]
@DamianFekete the mentioned behavior present on `Ctrl|Command+Enter` on stock VS Code.

This behavior conflicts with our hotkey that used for quick build/run. I suggest something like `Shift+Enter` for `editor.action.insertLineAfter`.

Is it ok for you?

**Comment by DamianFekete** [comment]
@x1unix, yes, `Shift+Enter` is what I would like.

I though that `Shift+Enter` was the default in VS Code, 
![image](https://user-images.githubusercontent.com/150717/163567110-69147413-34e4-416f-8487-edcd5d2b8fdf.png)


but it may not be (source seems to be Extension, although above I see "default keybinding"):
![image](https://user-images.githubusercontent.com/150717/163566951-87432ef0-2190-468d-9467-a918238581cc.png)

I'm not really a VS Code user.

**Comment by x1unix** [comment]
@DamianFekete see: https://github.com/x1unix/go-playground/pull/158
