### ISSUE TITLE
Errors reported on the wrong line number

### ISSUE THREAD

**Issue by DamianFekete** [x1unix/go-playground#161]
I assume that the code is getting formatted first and only _after_ that the analysis of the code is performed. Because of this, the line information can be wrong. A simple example to reproduce this:

![image](https://user-images.githubusercontent.com/150717/163601113-0863fe78-4baa-4938-8570-ed550cad229d.png)

**Comment by x1unix** [comment]
@DamianFekete it's an error from Go playground server compiler. I have nothing to do with this.

Try to use WebAssembly runtime
