### ISSUE TITLE
Display an easy-to-notice warning when code contains `time.Now()` that the values won't be as expected

### ISSUE THREAD

**Issue by mikeschinkel** [x1unix/go-playground#189]
Since `time.Now()` will not be fixed to work as expected (see #104, #188), please consider adding **an easy-to-notice warning** that the code will not operate as expected?  

That would keep developers from spending a lot of time trying to figure out what the hell is wrong with their code only to realize that the problem is not necessarily their code but in-fact a known-bug in how to platform diverges from expectation.  

And it would be [yet another benefit to using goplay.tools vs. golang.org/play](https://stackoverflow.com/a/28143445/102699).

**Comment by x1unix** [comment]
@mikeschinkel how do you see that to be implemented?

**Comment by mikeschinkel** [comment]
How about something as simple as this?  When the use clicks "Run" your code does a text search for `time.Now()` and if found appends a warning message to the output tile like shown in this screenshot:
<img width="1445" alt="CleanShot 2022-07-07 at 17 05 38@2x" src="https://user-images.githubusercontent.com/153285/177871371-68b1ffa5-73ca-4fb9-94bd-41c5ba1f4909.png">

**Comment by x1unix** [comment]
@mikeschinkel thank you for a report. I'll consider to add some kind of similar notification.

Btw currently I'm planning to add [yaegi](https://github.com/traefik/yaegi)-based runtime so sandbox can work fully offline.

For now, I can recommend to use WebAssembly environment but it might have some I/O limitations (filesystem, networking).

<img width="947" alt="image" src="https://user-images.githubusercontent.com/9203548/177872670-bc0efbee-506a-44fc-86ed-0ab8eac71709.png">

**Comment by mikeschinkel** [comment]
Thank you for considering.

> For now, I can recommend to use WebAssembly environment 

Thank you. 

However I did not offer this suggestion for myself, because now run into the problem I now know how to avoid it  and just do my learning related to the `time` package using my GoLand IDE.

I suggested the change for the benefit of people in the future who come to goplay.tools who have no idea of the limitation, and when things don't work as expected they assume their code is the problem, not the platform.  

And for that reason, it would never occur to them that they would need to open up the settings, click the environment tab and switch to WebAssembly for `time.Now()` to return a correct result.

Said another way, I made the suggestion so that goplay.tools might become more consistent with the [principle of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) when someone who was trying to learn how to format time values used goplay.tools in conjunction with`time.Now()`.  #fwiw 

----

As a complete aside, I notice you are from Lviv, Ukraine. How are things going for you, your family and your community given the war of Russian aggression?  My heart goes out to your country people and I hope for your collective benefit that there is a resolution to the war soon than later.

**Comment by x1unix** [comment]
@mikeschinkel I propose to show this warning as a warning in code editor. It should mark all points where `time.Now()` is used with explanation.

What do you think?

<img width="900" alt="image" src="https://user-images.githubusercontent.com/9203548/197316936-b21f8c45-1208-4249-8296-17ba0bf18b5c.png">

**Comment by mikeschinkel** [comment]
Perfect!

**Comment by x1unix** [comment]
Will be shipped in a next release.
