### ISSUE TITLE
Vim keybind `:w[rite]` as a shortcut to run the code

### ISSUE THREAD

**Issue by ian-h-chamberlain** [x1unix/go-playground#192]
Thanks for this playground, Vim mode was the killer feature I have been looking for that sets this playground well above any other I have used!

On macOS, I can easily enough use `⌘+⏎` as a shortcut to run the code on the playground, which is nice. I have muscle memory for `:w` (`:write`) in Vim's normal mode to save a file, so it would be nice if this was also a shortcut for the same action.

As it stands, it seems the `:w` command is _recognized_ somehow. I don't see an error like the following:
![Screen Shot 2022-08-09 at 13 20 50](https://user-images.githubusercontent.com/11131775/183716567-ef113e78-dc63-43de-8ce1-82a7fc44ef4e.png)
However, it doesn't appear to actually do anything (format / submit). Would you consider a change to map `:w` as a shortcut meaning the same as `cmd+enter`?

**Comment by x1unix** [comment]
Hello @ian-h-chamberlain and thank you for the feedback.

The `⌘+⏎` shortcut and VIM commands are implemented in different way.

A quick run shortcut is actually a [monaco editor action](https://github.com/x1unix/go-playground/blob/master/web/src/components/editor/CodeEditor.tsx#L80).

The vim mode is actually a [hacky adapter](https://github.com/x1unix/go-playground/blob/master/web/src/plugins/vim/editor.ts#L33) that listens for commands on top of monaco.

This implementation is actually a port of other vim-emulation library and command handler is implemented inside that library.

But I'll try to look into that.

**Comment by ian-h-chamberlain** [comment]
Thanks for the quick response! From [their README](https://github.com/brijeshb42/monaco-vim#defining-ex-mode-command), it looks like you might just be able to bind an ex mode command to wire up the submit action, as long as the `:<cmd><Enter>` keypresses still end up propagating to the `VimMode` handler? Thanks for looking into it!

**Comment by x1unix** [comment]
@ian-h-chamberlain thank you for the research :)

**Comment by x1unix** [comment]
Will be shipped in a next release.
