### ISSUE TITLE
Compare several versions of golang

### ISSUE THREAD

**Issue by halmai** [x1unix/go-playground#207]
I would like to compare how a particular go code is running with different versions of golang. Unfortunately, https://go.dev/play/ allows to pick only the most recent versions of go (currently `v1.19`, `v1.20` and the `dev branch`). https://goplay.tools is even poorer, it doesn't allow to pick anything. 

By contrast, https://3v4l.org/iL2eV for PHP allows to compare all current and past versions of PHP. 

I would like to do something similar with go. For example, I would like to see 

```
package main

import (
	"fmt"
	"math/big"
)

func main() {
	x := big.Rat{}
	y, _ := x.SetString("0")
	fmt.Printf("%+v %+v\n", x, y)
}
```

printing 
`{a:{neg:false abs:[]} b:{neg:false abs:[]}} 0/1` with `go 1.18.3` and
`{a:{neg:false abs:[]} b:{neg:false abs:[1]}} 0/1` with `go 1.19.3`.

**Comment by x1unix** [comment]
@halmai addressed in #213
