### ISSUE TITLE
Fail to perform concurrent blocking operations 

### ISSUE THREAD

**Issue by fresonn** [x1unix/go-playground#210]
Working with concurrency, I noticed that there is no blocking when performing certain operations.

First snippet:  https://goplay.tools/snippet/gVEdxKMwGOe
Second snippet: https://goplay.tools/snippet/QTpxrMuSmgg

Code will execute immediately without blocking logic

**Comment by x1unix** [comment]
@fresonn fixed in #215 

Will be shipped in next release

**Comment by fresonn** [comment]
Great, your playground is already in my top bookmarks 👍
