### ISSUE TITLE
feature request: API to create new snippet

### ISSUE THREAD

**Issue by golightlyb** [x1unix/go-playground#249]
It would be great if we could create a go-playground example by sending a HTTP POST request of some code, and get a snippet ID in return, instead of having to create a playground share link manually.

Thanks for your consideration!

**Comment by x1unix** [comment]
@golightlyb The project uses the original Go Playground API to create snippets. See [`goplay.Share`](https://github.com/x1unix/go-playground/blob/master/pkg/goplay/methods.go#L40) method.
