### ISSUE TITLE
Installation failure on local machine

### ISSUE THREAD

**Issue by wyattbiker** [x1unix/go-playground#262]
Followed the instructions to install with git clone.
```
git clone https://github.com/x1unix/go-playground.git
cd go-playground
make
sudo make install
```

 Any ideas why when I run make I get the error below? Thanks
```
~/goproj/go-playground (master)$ make
:: Cleanup...
:: Checking and installing dependencies...
Ambiguous Syntax Error: Cannot find which to pick amongst the following alternatives:

  0. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]
  1. yarn install [--json] [--immutable] [--immutable-cache] [--check-cache] [--inline-builds] [--mode #0]

While running --cwd=./web install --silent
make: *** [build.mk:43: preinstall] Error 1
~/goproj/go-playground (master)$ 
```

**Comment by x1unix** [comment]
@wyattbiker probably you have more than `yarn` packages installed on your system.

I recommend using Docker container to run the service locally.

* https://github.com/x1unix/go-playground/pkgs/container/go-playground%2Fgo-playground
* https://hub.docker.com/r/x1unix/go-playground

**Comment by wyattbiker** [comment]
@x1unix hmmm, don't know how it happened. Did a global find and I got this. 

```
~$ which yarn
/usr/local/bin/yarn
~$ whereis yarn
yarn: /usr/local/bin/yarn
```

```
file:///usr/local/bin/yarn
file:///usr/share/nodejs/yarn
file:///home/user1/.cache/node/corepack/yarn
file:///usr/share/nodejs/yarn/bin/yarn
file:///usr/local/lib/node_modules/corepack/shims/yarn
file:///usr/local/lib/node_modules/corepack/shims/nodewin/yarn
```

Was trying to avoid running a docker process though.  I may go with the docker option.

**Comment by x1unix** [comment]
@wyattbiker If you still wish to avoid using Docker, try to remove global yarn installation (nowadays people use `npx ...` to run local packages).

`npm uninstall -g yarn`
