### ISSUE TITLE
Where does file writing/reading happen when running with Docker?

### ISSUE THREAD

**Issue by wyattbiker** [x1unix/go-playground#263]
I installed with docker and run in browser `http://localhost:8282`
I want to write a file. But when I run this code, but there is no file created in /tmp/dat1.  Is there some volume I am supposed to attach to?

```go
package main

import (
	"os"
)

func check(e error) {
	if e != nil {
		panic(e)
	}
}

func main() {

	d1 := []byte("hello\ngo\n")
	err := os.WriteFile("/tmp/dat1", d1, 0644)
	check(err)
}
```

**Comment by x1unix** [comment]
@wyattbiker code is running in isolated environment. By default it's executed by an official Go playground server.

You can still read files inside your program ([example](https://goplay.tools/snippet/LrG0vLkLEj-)).
