### ISSUE TITLE
output is not cleared if second run outputs nothing

### ISSUE THREAD

**Issue by dear3vil** [x1unix/go-playground#264]
If I run my code and output is generated and then do another run without any output, the output is not cleared and still shows the previous results, which might be confusing.

Run once, set output to false and run again, output still shows Hello World instead of being empty:
https://goplay.tools/snippet/inNWqvG_K6Q

**Comment by x1unix** [comment]
@dear3vil I can't reproduce the issue. Can you please provide a demo?


https://github.com/x1unix/go-playground/assets/9203548/a9010a83-c4b2-49d0-b957-fe13d6a04add

**Comment by dear3vil** [comment]
@x1unix 
Please check attached video, I'm using the latest version of Firefox. Just tried with an untouched Edge Browser, same result.
https://github.com/x1unix/go-playground/assets/138237715/13cfb6e3-6e65-48c7-a994-0b556a30daf2

**Comment by x1unix** [comment]
@dear3vil thanks for reporting the issue!
