### ISSUE TITLE
wails

### ISSUE THREAD

**Issue by ddkwork** [x1unix/go-playground#280]
Can you nake a wails + vue simple

**Comment by x1unix** [comment]
@ddkwork what?

**Comment by ddkwork** [comment]
> @ddkwork what?

https://primevue.org/
https://wails.io/

Use primevue creat left dir tree, and the terminal https://primevue.org/terminal
On the bottom,  use labs to open more file, last use wails creat binary file.

**Comment by x1unix** [comment]
@ddkwork Currently there is no plan to replace React with Vue as it will require a complete rewrite of the frontend part.

Also, I don't see a point in using Wails for a web app.
