### ISSUE TITLE
Force re-download of a package?

### ISSUE THREAD

**Issue by mikeschinkel** [x1unix/go-playground#284]
I am wanting to use GoPlay.tools in my `README.md` for some of my projects, but I am finding that once you download my package if I make any last minute changes your online service continues to use the old one.

Is there a way to get it to re-download a package?   Failing that, how long is the timeout before it will clear the cache and allow for downloading again?

**Comment by x1unix** [comment]
@mikeschinkel hello, what execution mode do you use?

<img width="293" alt="image" src="https://github.com/x1unix/go-playground/assets/9203548/19794f90-76e9-4ef6-8692-373fd291e23a">

Using any option from the **Run on server** group means that code is running on the official Go playground server and I can't change this behavior.

As an alternative, I can propose using **Go Interpreter** option which will download the latest package from Go module proxy but you have to ensure that Go module proxy knows about your latest package version.
