### ISSUE TITLE
support running code in 32-bit mode

### ISSUE THREAD

**Issue by bruceauyeung** [x1unix/go-playground#287]
looks like running code in 32-bit mode is missing, it would be very helpful to support this when user code behaves differently between 32-bit mode and 64-bit mode.
thanks for the great and lovely playground.

**Comment by bruceauyeung** [comment]
@x1unix I found the feature lack in `run on server` mode.
is it possible to support this in `run in browser` mode ? does it depends on whether web browser is 32 bit or not?

**Comment by x1unix** [comment]
@bruceauyeung the "in browser mode" uses WebAssembly which supports 32bit and 64bit numbers. I believe it's host-independent as WASM is a cross-platform solution.

The playground doesn't cover platform-specific configurations. I would recommend you to use VM or [Compiler Explorer](https://godbolt.org/) if you need to test your code against multiple different configurations.
