### ISSUE TITLE
Chrome freezes when attempting to copy text.

### ISSUE THREAD

**Issue by waj334** [x1unix/go-playground#289]
For any program, attempting to copy text by either CTRL+C or select "Copy" from the right-click context menu after selecting some text causes the session to freeze, forcing me to reload the tab and lose my work in the process. The freeze seems to occur before any text is actually copied.

**Comment by x1unix** [comment]
@waj334 

Please provide some information about your environment:

* OS Version
* Browser version
* Can you replicate the issue on different machines?

**Comment by Ramezaan7** [comment]
Hello
