### ISSUE TITLE
Access to files outside the playground project

### ISSUE THREAD

**Issue by MrErlison** [x1unix/go-playground#311]
When I was studying templates, I made an example with the text/template package and was able to read some files from the playground operating system, such as hosts, /proc/ etc.

https://goplay.tools/snippet/TPLrvrFb2pZ

**Comment by x1unix** [comment]
@MrErlison did you ran the program on a server environment?

<img width="269" alt="image" src="https://github.com/x1unix/go-playground/assets/9203548/57bf1f8a-5396-40bf-b730-dab3f683c89e">

If true - those requests are served by the [original Go Playground](https://go.dev/play).

If you consider this as a security issue - please address this issue on the official Go bug tracker.

**Comment by x1unix** [comment]
Indeed, a lot of host stuff is available:

https://goplay.tools/snippet/Re3n9OCl_pb
