### ISSUE TITLE
timeout running previous version (1.21) with hello world example

### ISSUE THREAD

**Issue by dangogh** [x1unix/go-playground#338]
Running Chrome 124.0.6367.210 on macos (macbook air M2).   Using the initial "hello world", I switched the Go version to 1.21 (previous version) running on the server.

I get `Error
timeout running program
` in the output window.

Current version and dev version both run and produce expected output.

Also tried using Firefox 126.0 on the same machine with the same timeout result.

**Comment by x1unix** [comment]
@dangogh please provide a snippet to reproduce a problem.

**Comment by x1unix** [comment]
@dangogh Go 1.21 programs are proxied to original Go Playground server.

Looks like there is an issue on a Google side - https://go.dev/play/p/MAohLsrz7JQ?v=goprev
Please address issues to them as they host the service.

<img width="1722" alt="image" src="https://github.com/x1unix/go-playground/assets/9203548/623091f9-9649-4f65-b293-a12737882d7c">


Meanwhile, if you want to run some simple programs without third-party dependencies - please try WebAssembly mode which also use Go 1.21. Program will be executed on your machine directly.

**Comment by dangogh** [comment]
@x1unix thanks -- I'll follow up there.  Closing this to not distract...
