### ISSUE TITLE
Why use golang.org remotely to compile?

### ISSUE THREAD

**Issue by liuzeng01** [x1unix/go-playground#34]
Could support to use my local go SDK to compile and run?

{"level":"error","ts":1597641677.3137167,"logger":"langserver","caller":"langserver/server.go:216","msg":"failed to contact Go Playground - Post \"https://play.golang.org/fmt\": dial tcp 216.239.37.1:443: connect: connection refused","stacktrace":"github.com/x1unix/go-playground/pkg/langserver.(*Service).HandleRunCode\n\t/tmp/playground/pkg/langserver/server.go:216\ngithub.com/x1unix/go-playground/pkg/langserver.WrapHandler.func1\n\t/tmp/playground/pkg/langserver/middleware.go:22\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2041\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2836\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1924"}

**Comment by x1unix** [comment]
@liuzeng01 you can switch to WebAssembly in settings window.
WASM builds are compiled by server itself and executed by browser, but some features will be unavailable: external packages support, some IO limitations, etc.

Also, you can use local [Go playground backend](https://github.com/golang/playground) (just change playground URL in [code](https://github.com/x1unix/go-playground/blob/master/pkg/goplay/client.go#L35)

![image](https://user-images.githubusercontent.com/9203548/90387166-5c7e9980-e08e-11ea-9079-886a656697f4.png)

**Comment by x1unix** [comment]
@liuzeng01 added custom Playground URL option support. You can deploy Go playground locally and specify local instance URL.

See: https://github.com/x1unix/go-playground/pull/38

**Comment by liuzeng01** [comment]
OK ,I just had a try with the docker from the docker-hub ,And then I will have a try with those methods

**Comment by x1unix** [comment]
@liuzeng01 you can specify local playground URL with `APP_PLAYGROUND_URL` env variable

https://github.com/x1unix/go-playground/wiki/Docker
