### ISSUE TITLE
No usable shortcuts for run and build

### ISSUE THREAD

**Issue by prochac** [x1unix/go-playground#40]
https://play.golang.org/ uses [ctrl]+[enter] as a shortcut for build to validate the code and [ctrl]+[shift]+[enter] fot run to see output.
In https://goplay.tools/, the alt text of Run button says F5, that's not a good shortcut for a browser environment.

**Comment by x1unix** [comment]
@prochac why `F5` shortcut is not good? That shortcut duplicates VSCode behavior

**Comment by prochac** [comment]
It's well common known shortcut for a page refresh

**Comment by x1unix** [comment]
@prochac resolved in https://github.com/x1unix/go-playground/pull/41

**Comment by x1unix** [comment]
@prochac deployed changes to https://goplay.tools
