### ISSUE TITLE
[bug usability] Multiple cursors bug on phone

### ISSUE THREAD

**Issue by cata0309** [x1unix/go-playground#59]
On phone I experience the following issue, I tap to a position in the editor and sometimes the old position remains in its position 
![Screenshot_20210516-020650533](https://user-images.githubusercontent.com/35623921/118380597-abd90280-b5eb-11eb-8773-1f8079bc1077.png)

**Comment by x1unix** [comment]
@cata0309 please report the issue to https://github.com/microsoft/monaco-editor
