### ISSUE TITLE
Make project UX more comfortable

### ISSUE THREAD

**Issue by icecream78** [x1unix/go-playground#6]
I purpose make button`s "Share" logic more comfortable. I think, it will be great to show pop with link or something like that

**Comment by x1unix** [comment]
@icecream78 can be considered in future releases

**Comment by TomYeoman** [comment]
Would be great to see a save to github type feature

**Comment by x1unix** [comment]
@TomYeoman I recommend to create a dedicate issue for that. Also btw this is an open-source project so any contribution is welcome.

**Comment by vuon9** [comment]
Would be very nice if the `app-preview` container's height can be adjustable

**Comment by x1unix** [comment]
@vuon9 what container do you mean? Console output container?

**Comment by vuon9** [comment]
> @vuon9 what container do you mean? Console output container?

yes!

**Comment by x1unix** [comment]
@vuon9 this is in plans, thank you for the feedback!

**Comment by x1unix** [comment]
@vuon9 @icecream78 implemented in https://github.com/x1unix/go-playground/pull/92 and will be shipped in the next stable release.

**Comment by vuon9** [comment]
thank you! <3 @x1unix
