### ISSUE TITLE
installation issues `make: *** [build.mk:12: collect-meta] Error 1`

### ISSUE THREAD

**Issue by smjure** [x1unix/go-playground#67]
Great project, thank you. I wanted to install a local instance but many issues along the way. After installing npm, yarn, nodejs, i got this error which i could not overcome:
```
cd ./web && yarn install --silent
Downloading page from "https://golang.org/pkg"...
Parsing page...
TypeError: Cannot read property 'querySelector' of null
    at collectAllPackages (/home/oem/Downloads/go-playground/tools/collector/domCollector.js:36:22)
    at parseGoDocPage (/home/oem/Downloads/go-playground/tools/collector/domCollector.js:65:16)
    at main (/home/oem/Downloads/go-playground/tools/collector/index.js:17:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
make: *** [build.mk:12: collect-meta] Error 1
``` 
Any suggestions? Thank you.

**Comment by x1unix** [comment]
@smjure this is a package documentation collector issue. It used to parse GoDoc site, but seems like that it was completely replaced by a new pkg.go.dev website.
I have a plan to drop this script and just collect Go SDK documentation from the source code.

As a temporary solution, please try to extract `packages.json` from a docker image (or just use [docker image](https://hub.docker.com/r/x1unix/go-playground)):

```
docker create x1unix/go-playground  # returns container ID
docker cp $container_id:/opt/playground/data/packages.json packages.json
docker rm $container_id
```

[packages.json](https://github.com/x1unix/go-playground/files/6959309/packages.json.txt)

**Comment by x1unix** [comment]
Fixed by https://github.com/x1unix/go-playground/pull/68
