### ISSUE TITLE
installation issues :make: *** [preinstall] Error 254

### ISSUE THREAD

**Issue by Desire99** [x1unix/go-playground#69]
I wanted to install a local instance but many issues along the way. After installing npm, yarn, nodejs, i got this error which i could not overcome:
`➜  go-playground git:(master) ✗ make
rm -rf ./target && rm -rf ./web/build
- Installing dependencies...
cd ./tools/collector && npm install --silent
make: *** [preinstall] Error 254`

**Comment by x1unix** [comment]
Fixed by https://github.com/x1unix/go-playground/pull/70

**Comment by x1unix** [comment]
@Desire99 I recommend you to take a look at official Docker image: https://hub.docker.com/r/x1unix/go-playground
