### ISSUE TITLE
fmt.Printf()

### ISSUE THREAD

**Issue by lrweck** [x1unix/go-playground#76]
Hi!

Printing with fmt.Printf("%+v", myStruct) shows nothing on the console output.

fmt.Println() works fine

**Comment by x1unix** [comment]
@lrweck hi. Are you using WASM runtime or the default one (specified in settings).

Can you share please a snippet?

**Comment by karanssh** [comment]
https://goplay.tools/snippet/Z7mmkYc4Frj

I tried it now, but I was not able to reproduce it, it seems to show up fine for me on this simple snippet

**Comment by karanssh** [comment]
@x1unix , re-verified on macOS mojave with google chrome - not able to repro this bug.

**Comment by x1unix** [comment]
@karanssh thank you for a reply. Closing the ticket for now.
