### ISSUE TITLE
Support for multiple files

### ISSUE THREAD

**Issue by akshaybharambe14** [x1unix/go-playground#78]
[The Go Playground](https://play.golang.org/) supports multiple files in editor. It will be great to have that feature.

See [example](https://play.golang.org/p/rq4J90MxTKJ).

**Comment by akshaybharambe14** [comment]
The example for multiple files from official playground works here too (I assume we are calling official playground APIs).

See https://goplay.tools/snippet/rq4J90MxTKJ

I think we need better UX to handle multiple files. We get `expected declaration, found '--'` error in above example.

**Comment by x1unix** [comment]
@akshaybharambe14 seems like you enabled WebAssembly runtime (and wasm code gets compiled by Go compiler on server).

![image](https://user-images.githubusercontent.com/9203548/134822214-27d3dfcd-ab2c-437e-b5a1-7fc1537de993.png)

Checked with regular Go playground runtime and it's working.

I was thinking about implementing multiple tabs for this functionality and mb implement this when will have some spare time

**Comment by akshaybharambe14** [comment]
> The example for multiple files from official playground works here too (I assume we are calling official playground APIs).
> 
> See https://goplay.tools/snippet/rq4J90MxTKJ
> 
> I think we need better UX to handle multiple files. We get `expected declaration, found '--'` error in above example.

**Comment by x1unix** [comment]
Will be shipped in v2.0.0
