### ISSUE TITLE
embedding / iframing https://goplay.tools/

### ISSUE THREAD

**Issue by janhalfar** [x1unix/go-playground#79]
Dear Denis - awesome work - thanks for writing it!!!

I am playing around with a new documentation website and I would love to embed goplay.tools using an iframe. 

First of all, is that ok for you? 

If so, here is the sandboxing error that I get: "Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document."

<img width="899" alt="Screenshot 2021-11-12 at 18 21 58" src="https://user-images.githubusercontent.com/204854/141508406-f4cc2fb9-b1bc-4ec3-8401-f9461bd1d911.png">

**Comment by x1unix** [comment]
Hi @janhalfar.

Can you tell me please:
* What browser version and os are you using? Probably it's a Chromium based version.
* Do you have any content-blocking extensions enabled (like uBlock origin)? If yes - please try without them.

I tried to reproduce the issue on Firefox 94 and the latest Google Chrome but everything seems to work fine.

![image](https://user-images.githubusercontent.com/9203548/141656366-d81aa316-5ef8-4e11-a126-d284d53eed4c.png)

https://codepen.io/cyberd/pen/qBXJazW

**Comment by janhalfar** [comment]
Hi @x1unix,

latest Chrome version - it turns out, that it was the "Block third-party cookies" setting, that killed local storage ...

I also checked with latest Safari and Firefox and can confirm that it is working.

I still would recommend to wrap local storage access in a try catch block, so that the case is handled gracefully.

Cheers,

Jan

**Comment by x1unix** [comment]
@janhalfar thank you for reply, will add `try/catch` in a next release
