### ISSUE TITLE
Blank Tab on duplicating current tab

### ISSUE THREAD

**Issue by sachin120** [x1unix/go-playground#80]
On Duplicating the current tab in chrome, the duplicated tab is blank

1] Original tab
![image](https://user-images.githubusercontent.com/35319163/143172833-2fde8ab4-8416-49e5-bbfa-1711ce7022e7.png)

2] Duplicated tab
![image](https://user-images.githubusercontent.com/35319163/143172904-d67d6e2a-c3dd-4fa4-9aad-805edc75aec3.png)

**Comment by x1unix** [comment]
@sachin120 not sure that this is an issue on our side. Can you at least inspect "Console" section in dev tools?

**Comment by sachin120** [comment]
@x1unix I tried with inspect "Console". On chrome, once I hit `F12` key (for debug mode) screen is loaded normally ...

**Comment by sachin120** [comment]
But still, on duplicating the tab I get it every time. The send screenshot

**Comment by x1unix** [comment]
@sachin120 I'm unable to reproduce this on a latest Chrome 97.0.4692.99 (Official Build)

![Screen Recording 2022-02-08 at 12 18 37](https://user-images.githubusercontent.com/9203548/152967627-3df933cb-e896-453c-81de-e8d36f1e1896.gif)
