### ISSUE TITLE
can output window be scrollable and resizeable if possible

### ISSUE THREAD

**Issue by sachin120** [x1unix/go-playground#81]
It would be nice if the output section is resizeable and scrollable

![image](https://user-images.githubusercontent.com/35319163/143174279-669dd25f-b989-48b9-8467-4b1226f704f0.png)

**Comment by x1unix** [comment]
@sachin120 output section is already scrollable.

Resize is implemented in #89 and will be shipped in a next stable release

**Comment by sachin120** [comment]
Thank you Denis 🙏 :-)
