### ISSUE TITLE
Web application was updated, click Reload to apply changes.

### ISSUE THREAD

**Issue by gogoods** [x1unix/go-playground#83]
![image](https://user-images.githubusercontent.com/3422759/146354292-fc50ae1d-7643-4ce4-af14-ee693664acf0.png)

As you see above, I clicked the Action button and page refreshed, but the message still appears.

What can I do to close it?

**Comment by x1unix** [comment]
@gogoods can you try to do a hot reload (`ctrl+shift+r` or `ctrl+F5`) please and tell me if it helps?

**Comment by gogoods** [comment]
@x1unix 
unfortunately, force reload doesn't work ( ctrl+shift+r , ctrl+F5, disable cache to refresh)

😂

**Comment by dmwin72015** [comment]
me too

**Comment by x1unix** [comment]
@gogoods https://github.com/x1unix/go-playground/pull/96 resolves this issue and will be shipped in the next stable release.

**Comment by x1unix** [comment]
@gogoods @dmwin72015 as I see, you're a native chinese speaker. What do you think about chinese translation of the web interface?

If yes - can you help me please with translation process?

**Comment by gogoods** [comment]
@x1unix 
sure, it's my pleasure.
even thought i think there is no need to translate the web ui lanuage to chinese for a programer.
we all are coder, right?
